<?xml version="1.0"?>
<robot name="itls_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Define robot constants -->
  <xacro:property name="base_width" value="1.3005"/>
  <xacro:property name="base_length" value="4.136"/>
  <xacro:property name="base_height" value="1.3"/>
  <xacro:property name="base_link_to_front" value="2.3715"/>
  <xacro:property name="wheel_radius" value="0.14"/>
  <xacro:property name="base_length_actual" value="2.64"/>
  <xacro:property name="base_link_to_lidar_rear" value="-1.28"/>

  <!-- Robot Base -->

  <link name="base_link">
    <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 ${pi/2.0}"/> 
  </link>
  
  <link name="robot_center"> 
    <visual>
      <geometry>
        <box size="${base_length_actual} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Orange">
        <color rgba="1.0 0.5 0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length_actual} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="1500" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>
  <joint name="base_link_T_robot_center" type="fixed">
    <parent link="base_link"/>
    <child link="robot_center"/>
    <origin xyz="${base_link_to_lidar_rear + base_length_actual/2.0} 0.0 ${base_width/2.0}" rpy="0.0 0.0 0.0"/>
  </joint>


  <link name="base_link_front"> </link>

  <joint name="base_link_T_base_link_front" type="fixed">
    <parent link="base_link"/>
    <child link="base_link_front"/>
    <origin xyz="${base_link_to_front} 0.0 0.0" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="base_link_back"> </link>

  <joint name="base_link_T_base_link_back" type="fixed">
    <parent link="base_link"/>
    <child link="base_link_back"/>
    <origin xyz="${base_link_to_front - base_length} 0.0 0.0" rpy="0.0 0.0 ${pi}"/>
  </joint>

  <!-- Robot Footprint -->

  <link name="base_footprint"/>
  <joint name="base_link_T_base_footprint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-wheel_radius}" rpy="0 0 0"/>
  </joint>


</robot>  