  apt-get install -y cmake
  apt-get install -y python3-twisted
  apt-get install -y ros-humble-actionlib-msgs
  apt-get install -y ros-humble-ament-cmake
  apt-get install -y ros-humble-ament-cmake-python
  apt-get install -y ros-humble-ament-cmake-ros
  apt-get install -y ros-humble-ament-lint-auto
  apt-get install -y ros-humble-ament-lint-common
  apt-get install -y ros-humble-angles
  apt-get install -y ros-humble-behaviortree-cpp
  apt-get install -y ros-humble-builtin-interfaces
  apt-get install -y ros-humble-common-interfaces
  apt-get install -y ros-humble-control-msgs
  apt-get install -y ros-humble-diagnostic-msgs
  apt-get install -y ros-humble-example-interfaces
  apt-get install -y ros-humble-geometry-msgs
  apt-get install -y ros-humble-joint-state-publisher-gui
  apt-get install -y ros-humble-launch
  apt-get install -y ros-humble-launch-ros
  apt-get install -y ros-humble-launch-xml
  apt-get install -y ros-humble-launch-yaml
  apt-get install -y ros-humble-lifecycle-msgs
  apt-get install -y ros-humble-message-filters
  apt-get install -y ros-humble-nav-msgs
  apt-get install -y ros-humble-plotjuggler-ros
  apt-get install -y ros-humble-rcl-interfaces
  apt-get install -y ros-humble-rclcpp
  apt-get install -y ros-humble-rclcpp-action
  apt-get install -y ros-humble-rclcpp-components
  apt-get install -y ros-humble-rclcpp-lifecycle
  apt-get install -y ros-humble-rclpy
  apt-get install -y ros-humble-rmw-cyclonedds-cpp
  apt-get install -y ros-humble-rmw-dds-common
  apt-get install -y ros-humble-robot-state-publisher
  apt-get install -y ros-humble-ros-gz
  apt-get install -y ros-humble-ros2launch
  apt-get install -y ros-humble-ros2node
  apt-get install -y ros-humble-ros2param
  apt-get install -y ros-humble-ros2pkg
  apt-get install -y ros-humble-ros2service
  apt-get install -y ros-humble-ros2topic
  apt-get install -y ros-humble-rosidl-default-generators
  apt-get install -y ros-humble-rosidl-default-runtime
  apt-get install -y ros-humble-sdl2-vendor
  apt-get install -y ros-humble-sensor-msgs
  apt-get install -y ros-humble-std-msgs
  apt-get install -y ros-humble-std-srvs
  apt-get install -y ros-humble-stereo-msgs
  apt-get install -y ros-humble-tf2
  apt-get install -y ros-humble-tf2-eigen
  apt-get install -y ros-humble-tf2-geometry-msgs
  apt-get install -y ros-humble-tf2-msgs
  apt-get install -y ros-humble-tf2-ros
  apt-get install -y ros-humble-tf2-sensor-msgs
  apt-get install -y ros-humble-trajectory-msgs
  apt-get install -y ros-humble-visualization-msgs
  apt-get install -y ros-humble-xacro  
